apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flux-service-cluster
  region: us-east-2
  version: "1.27"

availabilityZones: ["us-east-2b", "us-east-2c"]
managedNodeGroups:
  - name: workers
    amiFamily: AmazonLinux2023
    availabilityZones: ["us-east-2b"]
    instanceType: hpc6a.48xlarge
    volumeSize: 150
    volumeType: gp2
    minSize: 2
    maxSize: 2
    efaEnabled: true
    placement:
      groupName: performance-study
    labels: { "flux-operator": "true" }
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_eks.pub
